# Generated by Django 5.2.12 on 2026-03-17 07:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RobotDevice',
            fields=[
                ('device_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('line_name', models.CharField(max_length=20)),
                ('line_num', models.IntegerField()),
            ],
            options={
                'db_table': 'robot_devices',
            },
        ),
        migrations.CreateModel(
            name='RobotErrorLog',
            fields=[
                ('error_log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('error_code', models.CharField(max_length=50)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, to='api.robotdevice')),
            ],
            options={
                'db_table': 'robot_error_logs',
            },
        ),
        migrations.CreateModel(
            name='RobotErrorSession',
            fields=[
                ('session_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('final_status', models.CharField(default='ongoing', max_length=20)),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, to='api.robotdevice')),
                ('error_log', models.ForeignKey(db_column='error_log_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.roboterrorlog')),
            ],
            options={
                'db_table': 'robot_error_sessions',
            },
        ),
        migrations.CreateModel(
            name='RobotErrorChatHistory',
            fields=[
                ('chat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('step_no', models.IntegerField()),
                ('actor', models.CharField(max_length=20)),
                ('response_type', models.CharField(blank=True, max_length=30, null=True)),
                ('selected_choice', models.CharField(blank=True, max_length=1, null=True)),
                ('request_id', models.UUIDField()),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='api.roboterrorsession')),
            ],
            options={
                'db_table': 'robot_error_chat_histories',
            },
        ),
        migrations.CreateModel(
            name='RobotModel',
            fields=[
                ('model_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('manual_tag', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'robot_models',
                'unique_together': {('manufacturer', 'model_name')},
            },
        ),
        migrations.AddField(
            model_name='robotdevice',
            name='model',
            field=models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.CASCADE, to='api.robotmodel'),
        ),
        migrations.CreateModel(
            name='RobotErrorChecklistItem',
            fields=[
                ('checklist_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_order', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_presented', models.BooleanField(default=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('item_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='api.roboterrorsession')),
            ],
            options={
                'db_table': 'robot_error_checklist_items',
                'unique_together': {('session', 'item_order')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='robotdevice',
            unique_together={('line_name', 'line_num')},
        ),
    ]
