# Generated by Django 5.2.12 on 2026-03-17 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerCall',
            fields=[
                ('call_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, to='api.robotdevice')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='api.roboterrorsession')),
            ],
            options={
                'db_table': 'engineer_calls',
            },
        ),
    ]
