export const SAFETY_TIPS_KO = [
    "비상정지(EMO) 버튼의 위치를 조작 전에 항상 확인하십시오.",
    "로봇 구동 중에는 안전 펜스 내부로 절대로 진입하지 마십시오.",
    "용접 작업 구역 근처에는 인화성 물질을 절대 방치하지 마십시오.",
    "제어반 내부 전압이 완전히 방전(지연 시간 확인)된 후 커버를 여십시오.",
    "작업 종료 후 반드시 메인 전원을 차단하고 시건장치(LOTO)를 하십시오.",
    "안전 플러그가 해제된 상태에서는 자동 모드로 전환하지 마십시오.",
    "용접 아크 광선은 시력 손상을 유발하므로 차광 렌즈 헬멧을 착용하십시오.",
    "로봇 교시(Teaching) 중에는 항상 비상정지 스위치를 누를 준비를 하십시오.",
    "고무 절연 장갑 및 보호구를 착용하여 감전 사고를 예방하십시오.",
    "서보(Servo) 에러 해제 시 로봇의 갑작스러운 움직임에 주의하십시오.",
    "작업 전 소화기의 보관 위치와 사용 방법을 반드시 숙지하십시오.",
    "컨베이어 주변 작업 시 헐렁한 옷이나 장신구 착용을 금지하십시오.",
    "로봇의 가반 하중(Payload) 초과는 모터 과열 및 기계적 파손을 유발합니다.",
    "티칭 팬던트(TP) 와이어가 밟히거나 당겨져 손상되지 않도록 관리하십시오.",
    "안전 매트(Safety Mat)나 라이트 커튼의 센서 오염을 주기적으로 청소하십시오.",
    "인터록을 무단으로 해제하거나 우회하여 장비를 가동하지 마십시오.",
    "공압 서플라이 차단 시 잔압이 남아있을 수 있으므로 주의하십시오.",
    "장시간 근접 작업을 할 경우 환기 장치가 정상 작동하는지 확인하십시오.",
    "용접 토치 노즐의 스패터는 주기적으로 청소하여 가스 차폐율을 유지하십시오.",
    "툴(Tool) 교체 시 체결 볼트의 규정 토크를 반드시 준수하십시오.",
    "동절기 가동 초기에는 저속으로 웜업(Warm-up) 운전을 권장합니다.",
    "로봇 충돌 감지 센서가 정상적으로 작동하고 수치가 올바른지 점검하십시오.",
    "비상정지 버튼을 테스트할 때는 주변 작업자에게 미리 알리십시오.",
    "모터 냉각용 팬(Fan)의 먼지를 청소하여 과열 에러를 방지하십시오.",
    "용접 전원 장치에 접지(Earthing)가 확실하게 연결되어 있는지 확인하십시오.",
    "티칭 중에는 로봇의 가동 반경 내에 불필요한 공구를 두지 마십시오.",
    "모드 전환 락(Lock) 키는 안전 관리자만 소지하도록 관리하십시오.",
    "로봇 충돌 후에는 기구부 백래시 및 정밀도 오차를 측정하십시오.",
    "그리퍼(Gripper) 작동 압력을 정기적으로 체크하여 낙하 사고를 예방하십시오.",
    "낙하 방지 브레이크가 제대로 작동하는지 정기 점검이 필요합니다.",
    "용접 와이어가 피딩 튜브 내에서 꺾이거나 엉키지 않게 관리하십시오.",
    "로봇 베이스(Base) 고정 볼트의 풀림 현상이 없는지 육안 점검하십시오.",
    "서보 모니터링 화면에서 각 축의 토크 값을 주기적으로 관찰하십시오.",
    "라이트 커튼 투광/수광부에 이물질이 없어야 안전 감지가 정상 작동합니다.",
    "부식 우려가 있는 케이블 커넥터는 세척 후 방청 처리를 하십시오.",
    "로봇이 자중에 의해 처지는 현상이 있다면 브레이크 마모를 의심해 보십시오.",
    "용접 플렉시블 케이블의 피복이 타거나 벗겨지지 않았는지 점검하십시오.",
    "사용하지 않는 제어반 명판이나 구멍은 분진 유입 방지를 위해 밀폐하십시오.",
    "티칭 작업 시 로봇의 감속 모드(Reduced Speed)를 절대 해제하지 마십시오.",
    "냉각수 누수가 발생하면 전기 단락 위험이 있으므로 즉시 가동을 멈추십시오.",
    "안전 펜스 입구의 도어 인터록 키가 파손되었는지 정기 점검하십시오.",
    "컨트롤러 내부 배터리 전압 알람이 뜨면 30일 이내에 교체하십시오.",
    "용접 팁(Tip)의 소모 상태를 확인하고 필요시 드레싱 처리를 하십시오.",
    "과부하 정지가 빈번하다면 로봇 가속도(Acceleration) 값을 조정하십시오.",
    "티칭 팬던트 화면에 깨짐이나 터치 오류가 있는지 점검하십시오.",
    "로봇 동작 라인을 변경할 때는 타 로봇과의 간섭 구역 설정을 재검토하십시오.",
    "정전 후 전원이 복구되었을 때 로봇이 급출발하지 않도록 초기화하십시오.",
    "자동 운전 중 이상 소음이나 진동이 감지되면 즉시 가속을 줄이고 점검하십시오.",
    "와이어 돌출 길이(Stick-out)를 일정하게 유지하여 용접 품질을 높이십시오.",
    "안전화를 착용하여 발등 부상 및 미끄러짐 사고를 예방하십시오.",
    "비상 탈출을 막는 동선 상의 장애물은 즉시 치워주십시오.",
    "센서 케이블 분리 전 반드시 제어 전원을 Off 상태로 두십시오.",
    "그리퍼에 무거운 부하를 걸 때는 무게 중심(CoG)을 오프셋에 입력하십시오.",
    "유압 호스의 미세 누유는 압력 손실 및 심각한 고장을 초래합니다.",
    "안전 모듈(Safety Node)의 통신 LED 주기를 확인하여 결함을 조기 진단하십시오.",
    "가스 배관의 노후화를 확인하여 플렉스 가스 누출을 사전에 방지하십시오.",
    "안전 매트 위에 날카로운 물체를 적재하지 마십시오.",
    "용접 중 발생하는 가스는 슬래그 유입을 유발할 수 있으므로 상시 배기하십시오.",
    "보전 작업 시 반드시 사다리나 발판의 미끄럼 방지 처리 여부를 확인하십시오.",
    "로봇 암(Arm) 단부에 무리한 하중을 가하여 강제로 움직이려 하지 마십시오."
];

export const SAFETY_TIPS_EN = [
    "Always check the location of the Emergency Stop (EMO) button before operation.",
    "Never enter the inside of the safety fence while the robot is running.",
    "Never leave flammable substances near the welding work area.",
    "Open the cover only after the internal voltage of the control panel is fully discharged.",
    "After finishing work, make sure to cut off the main power and apply Lockout/Tagout (LOTO).",
    "Do not switch to automatic mode when the safety plug is disconnected.",
    "Welding arc light causes vision damage, so make sure to wear a welding helmet with shading lenses.",
    "Always be ready to press the emergency stop switch while teaching the robot.",
    "Wear rubber insulating gloves and protective gear to prevent electric shock accidents.",
    "Watch out for sudden movements of the robot when releasing servo errors.",
    "Before work, ensure you know the storage location and using method of fire extinguishers.",
    "Do not wear loose clothes or ornaments while working around conveyors.",
    "Exceeding the payload of the robot causes motor overheating and mechanical damage.",
    "Manage the teaching pendant (TP) wire so that it is not stepped on or pulled and damaged.",
    "Periodically clean sensor contamination on safety mats or light curtains.",
    "Do not operate equipment by releasing or bypassing interlocks unauthorized.",
    "Beware that residual pressure may remain when the pneumatic supply is cut off.",
    "When working in close proximity for a long time, check if the ventilation device is operating normally.",
    "Periodically clean spatters from the welding torch nozzle to maintain gas shielding rates.",
    "When replacing tools, strictly comply with the regulated torque of fitting bolts.",
    "During early winter operation, low-speed warm-up operation is recommended.",
    "Check if the robot collision detection sensor works normally and values are correct.",
    "Inform around workers in advance when testing the emergency stop button.",
    "Clean dust from the motor cooling fan to prevent overheating errors.",
    "Check if grounding is securely connected to the welding power source equipment.",
    "Do not put unnecessary tools within the operating radius of the robot during teaching.",
    "Manage the mode change lock key to be possessed only by the safety manager.",
    "After a robot collision, measure the backlash and accuracy error of the mechanism parts.",
    "Check the gripper operating pressure regularly to prevent falling accidents.",
    "Regular inspection is required to ensure that the fall prevention brake works properly.",
    "Manage welding wire so that it is not bent or tangled within the feeding tube.",
    "Visually inspect robot base fixing bolts for loose phenomena.",
    "Periodically observe the torque values of each axis on the servo monitoring screen.",
    "Safety detection operates normally only when there are no foreign substances on light curtains.",
    "Treat corroded cable connectors with anti-rust processing after washing.",
    "If the robot droops due to its own weight, suspect brake wear.",
    "Inspect the welding flexible cable for burnt or exfoliated covering.",
    "Seal unused control panel nameplates or holes to prevent dust inflow.",
    "Never release the reduced speed mode of the robot during teaching work.",
    "Stop operation immediately if cooling water 누수 occurs due to electrical short hazard.",
    "Inspect the door interlock key at the entrance of the safety fence regularly.",
    "If an internal battery voltage alarm pops up, replace it within 30 days.",
    "Check the consumption state of the welding tip and process dressing if necessary.",
    "If overload stops are frequent, adjust the robot acceleration value.",
    "Inspect the teaching pendant screen for breaking or touch errors.",
    "When changing robot motion lines, review interface zone setups with other robots.",
    "Initialize so that the robot does not start suddenly when power is restored after blackout.",
    "Reduce speed immediately and inspect if abnormal noise or vibration is detected.",
    "Maintain stick-out wire length uniformly to enhance welding quality.",
    "Wear safety shoes to prevent instep injuries and slip accidents.",
    "Immediately clear obstacles on paths that prevent emergency escape.",
    "Make sure to set control power Off before disconnecting sensor cables.",
    "When hanging a heavy load on the gripper, input the Center of Gravity (CoG) in offset.",
    "Micro-leakage of hydraulic hoses causes pressure loss and serious breakdown.",
    "Check the safety node communication LED cycles to diagnose defects early.",
    "Check gas piping aging to prevent flux gas leakages in advance.",
    "Do not stack sharp objects on top of safety mats.",
    "Continuously exhaust gas created during welding because it can cause slag inflow.",
    "Ensure non-slip treatment when using ladders or steps for maintenance work.",
    "Do not apply excessive load to the end of the robot arm to force movement."
];
