"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
load_dotenv(dotenv_path=PROJECT_ROOT / ".env")
load_dotenv()


def _env_first(*keys: str, default: str | None = None) -> str | None:
    for key in keys:
        value = os.getenv(key)
        if value is not None and str(value).strip():
            return str(value).strip()
    return default


def _to_bool(value: str | None, default: bool = False) -> bool:
    if value is None:
        return default
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


def _db_config() -> dict:
    if _to_bool(os.getenv("SSH_TUNNEL_ENABLED"), default=False):
        host = _env_first("SSH_LOCAL_BIND_HOST", default="127.0.0.1")
        port = _env_first("SSH_LOCAL_BIND_PORT", default="15432")
    else:
        host = _env_first("DB_HOST", _env_first("PGHOST", "localhost"))
        port = _env_first("DB_PORT", _env_first("PGPORT", "5432"))

    return {
        "HOST": host,
        "PORT": port,
        "NAME": _env_first("PGDATABASE", "postgres"),
        "USER": _env_first("PGUSER", "postgres"),
        "PASSWORD": _env_first("PGPASSWORD", ""),
    }

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
FRONTEND_DIST_DIR = BASE_DIR.parent / 'frontend_admin' / 'dist'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = _env_first("SECRET_KEY", "DJANGO_SECRET_KEY", default="django-insecure-local-dev-key")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',      # CORS 처리를 위한 라이브러리 추가
    'rest_framework',   # REST API 개발을 위한 라이브러리 추가(JSON 데이터 통신)
    'api',              # api 앱
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',            # CORS 처리를 위한 미들웨어 추가
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [FRONTEND_DIST_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        **_db_config(),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    FRONTEND_DIST_DIR / 'assets',
]
CORS_ALLOW_ALL_ORIGINS = True   # 모든 도메인에서의 요청을 허용


# ORM 쿼리 로그 출력 형식 지정
import sqlparse     # sql 쿼리를 조작

class SQLFormatter:
    def format(self, record):
        if record.sql:  # sql 로그이면
            # keyword_case='upper' : 키워드 대문자, reindent : 들여쓰기 적용
            formatted_sql = sqlparse.format(record.sql, reindent=True, keyword_case='upper')
            # record에 duration(처리하는데 걸린 총 시간) 속성이 있으면 사용, 없으면 0.0
            execution_time = getattr(record, 'duration', 0.0)   
            return f'{formatted_sql}\n[Execution Time: {execution_time:.3f} ms]'
        return record.getMessage()  # 일반 로그 메시지면 메시지 그대로 반환

# 로그 설정
# DB 쿼리 발생(logger가 감지) -> SQLFormatter함수를 통해 다듬기(Formatter가 가공) -> 터미널에 출력(Handler가 출력)
LOGGING = {
    'version': 1,                       # 로깅 설정 버전
    'disable_existing_loggers' : False, # 기존 로거 비활성화 여부
    'handlers' : {
        'console' : {
            'class' : 'logging.StreamHandler',  # 콘솔에 로그 출력
            'formatter' : 'custom_sql',         # 포맷터 설정
        },
    },
    'formatters' : {
        'custom_sql' : {
            '()' : SQLFormatter,    # 사용자 정의 포맷터 클래스 등록
        },
    },
    'loggers' : {
        'django.db.backends' : {
            'level' : 'DEBUG',          # DB 쿼리 로그는 DEBUG 레벨로 출력
            'handlers' : ['console'],   # console 핸들러 사용
        },
    },
}
